name: Run pylint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: actions/cache@v2
      with:
        path: ~/pip-cache
        key: pip-3.6-${{ github.sha }}
        # allow cache hits from previous runs of the current branch,
        # parent branch, then upstream branches, in that order
        restore-keys: |
          pip-3.6-
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip --cache-dir ~/pip-cache install pylint
    - name: Run Pylint
      run: |
        cd ./src/scripts/ && pylint --errors-only scripts
